### PR TITLE
Added Norway to the list of available VAT ID formats

### PR DESCRIPTION
**Pull request by artur-gajewski**

### CODE REVIEW

**Comment by ddeboer** [comment]
Thank you!

**Comment by willemstuursma** [comment]
Norway is not part of the EU @ddeboer. So the EU VAT rules for exporting goods / services from to EU don't apply when doing business with Norwegian organizations.

https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/zakendoen_met_het_buitenland/goederen_en_diensten_naar_andere_eu_landen/eu-landen_en_-gebieden/eu-landen_en_-gebieden

**Comment by ddeboer** [comment]
True, but we can still validate the VATs, right?

**Comment by willemstuursma** [comment]
Yeah, but you can't use the VIES validation service on these numbers.

If you had the assumption "@ddboer's libraries validated the VAT number, so I can use the EU VAT rules", this assumption is now broken. 

Given that the library implements the VIES service, this seems a reasonable assumption.

**Comment by ddeboer** [comment]
Good point. I see two possible solutions:
- we throw an exception when we cannot validate a VAT with VIES
- we remove support for Norwegian VATs completely.

**Comment by willemstuursma** [comment]
It depends on you - if you refocus the library on EU VAT numbers, the latter applies. Maybe a new major release would be in order.

If you just want to become a general purpose VAT validation library, you could focus on that but I guess the domain would need to be remodelled - for example US has sales tax per state.

**Pull request merged**
